const STORIES = [
  {
    id: 1,
    title: 'Arabia Into South Asia',
    period: '~70,000 years ago',
    character: 'Kavi',
    tagline: 'A coastal woman who sees opportunity beyond the endless desert',
    from: [48, 22],
    to: [73, 20],
    markerCoords: [58, 21],
    color: '#E8A838',
    bgGradient: 'linear-gradient(135deg, #7B4F16 0%, #C8860A 55%, #E8C47A 100%)',
    image: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?w=800&h=400&fit=crop',
    story: [
      `The ascent of the sun sent spiraling rays of light into the reed huts that Kavi and her families had been living in for the past few weeks. The crashing tides ebbed and flowed into the nearby tidepools, with the waves serving as a reminder that the day had begun. Kavi had been born near the coast, and that's all she'd ever known.`,
      `The harsh Arabian weather combined with endless desert meant her people were forced to live on the very outskirts of the Peninsula. Travelling together with her tribe from deposit to deposit, they had survived by gathering shellfish near freshwater tributaries and fishing along the coast. Recently, the tributary they'd camped alongside had been slowly drying up. Few clams remained within the tidepools, and the fish had begun to migrate across the coast. The tribe held a meeting to decide on what to do, but the elders were hesitant to travel further north away from the coast and cross a seemingly endless stretch of sand and rock. To do so would require travelling for weeks with little food or water and meant leaving the security of the coast to travel further inland.`,
      `But where the elders saw uncertainty and danger, Kavi saw opportunity. To leave behind the nomadic lifestyle they led which meant they were dependent upon the luck of the tides and instead create their own future. Influenced by her words, the rest of the tribe were eventually persuaded to pursue the journey into the desert. The members gathered water and the remaining seafood into reed satchels and began the slow trek over the first dune. First step at a time, Kavi's people made the first trek into South Asia.`,
    ],
  },
  {
    id: 2,
    title: 'South Into Southeast Asia',
    period: '~50,000 years ago',
    character: 'Ranu',
    tagline: 'A hunter who learned to read a world of leaves, pawprints, and fever',
    from: [80, 12],
    to: [107, 14],
    markerCoords: [98, 13],
    color: '#3DB86A',
    bgGradient: 'linear-gradient(135deg, #1B4332 0%, #40916C 55%, #74C69D 100%)',
    image: 'https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&h=400&fit=crop',
    story: [
      `What awoke Ranu was not the familiar noise of waves or the sound of squawking seagulls echoing overhead, but rather the sounds of leaves rustling in the wind. Overcrowding and rising tides had slowly pushed Ranu's tribe further into the tropical wilderness, forcing them to abandon the familiar seaside settlements they had previously inhabited.`,
      `The open sky and familiar shoreline gave way to a dense canopy buzzing with insects and strange creatures that Ranu hadn't ever encountered. The tribe was forced to repurpose their fishing spears and sharpen them against boars and panthers. Water, which was previously collected within freshwater streams, was now found by cutting apart entangling vines and draining trees of precious water. Yet not every problem was easily resolved within this new environment. A young child had fallen ill after eating a strange fruit, becoming delirious and developing a fever which only worsened with time. The persistent wave of insects and flies were a constant annoyance, carrying deadly diseases which brought down even the healthiest tribespeople.`,
      `When food became scarce, Ranu was forced to read the pawprints of animals to track down his next meal. The concentrated tribe eventually broke into various hunting groups, each occupying a section of the jungle. Generations of hunter-gatherers slowly passed down trails and maps, with each group expanding further into the dense canopy. Until one day, after thousands of years, Ranu's people reached the end of the jungle, and found the other end of the coasts.`,
    ],
  },
  {
    id: 3,
    title: 'Island Southeast Asia Into Sahul',
    period: '~65,000 years ago',
    character: 'Miri',
    tagline: 'A mother who watched her son sail toward an unknown continent',
    from: [120, -5],
    to: [135, -18],
    markerCoords: [128, -11],
    color: '#3A9BD5',
    bgGradient: 'linear-gradient(135deg, #023E8A 0%, #0077B6 55%, #48CAE4 100%)',
    image: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&h=400&fit=crop',
    story: [
      `A blue and open expanse of ocean stretches endlessly into the distance. Miri, a mother of two and one of the leaders of the tribe, gazes worriedly towards the coast. Her tribe had recently decided to venture across the islands they inhabited towards Sahul, an uncharted and largely unknown landmass spoken of only in legends. When the water receded and the sea level declined, islands would appear to ease the difficulty of the journey towards Sahul. But even then, reaching the land meant paddling in simple rafts across hundreds of miles of open water with no way to turn back.`,
      `As a mother, Miri worried about her oldest son, who had volunteered on the exploratory voyage. Who knew if his mind would survive weeks surrounded by nothing but endless waves, or whether the lashed-together logs would keep for long enough to reach shore. Yet the pressure of overpopulation and the outspoken youth had won over most of the tribe, and they were steadfast in the decision.`,
      `Years later, Miri's worries would finally be resolved. Reading a letter sent back by her son after first settlements were established in the new land, he described his struggles and triumph in overcoming the choppy waves, and in navigating using the stars to reach the right direction. Once they had reached shore, the tribesmen discovered a continent full of arid conditions and dangerous creatures. But over months, they began the slow process of adapting to the new environments, eventually reaching a semblance of stability. Miri and her son's story are one of boldness, where the first travelers into Australia did so with intention and purpose.`,
    ],
  },
  {
    id: 4,
    title: 'The Tibetan Plateau',
    period: '~30,000 years ago',
    character: 'Tawi',
    tagline: 'A man whose body held the key to survival at the roof of the world',
    from: [82, 34],
    to: [97, 31],
    markerCoords: [90, 32],
    color: '#9B72CF',
    bgGradient: 'linear-gradient(135deg, #3C096C 0%, #7B52AB 55%, #C7B8E8 100%)',
    image: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&h=400&fit=crop',
    story: [
      `Half of the group had already given up, descending back down into the valleys filled with withering shrubs and scarce food. Because for them, even barely habitable conditions were preferable to the conditions they had been subjected to in the Tibetan Plateau. More than 4,000 meters above sea level, the air has only 60% of the oxygen found at lower elevations. Snow glares constantly cause visual blindness for the travelers, and fuel is difficult to find.`,
      `Within these conditions, only Tawi is different from the rest. While the rest of his tribe struggle for breath on the harsh ascents in frigid conditions, he's able to do it without an issue. While the others stop to rest and recover, he decides to scavenge for usable tinder to light a fire. Over the course of weeks, Tawi slowly cements himself as a special case, having a constitution which seems uniquely adapted to survive within the harsh, oxygen-sparse conditions in the Plateau.`,
      `With his aid, the tribe manages to survive the first weeks within the frigid winter, managing to survive until springtime arrives. As the snow thaws and water begins to run down the sides of mountain cliffs, Tawi feels as though he's found a second home within the Tibetan Plateau. His genetic ancestry is passed down from generation to generation, eventually creating a people whose very genes have adapted to function with little oxygen, and whose constitutions are able to survive colder temperatures without entering shock.`,
    ],
  },
  {
    id: 5,
    title: 'Central Asia Into South Asia',
    period: '~4,000 years ago',
    character: 'Ashva',
    tagline: 'A pathfinder who bridged the world of the steppe and the city',
    from: [63, 42],
    to: [72, 28],
    markerCoords: [66, 37],
    color: '#E05C2A',
    bgGradient: 'linear-gradient(135deg, #4D2B0E 0%, #B5451B 55%, #E07B39 100%)',
    image: 'https://images.unsplash.com/photo-1518537073-8c6961bcd85e?w=800&h=400&fit=crop',
    story: [
      `Ashva, a daughter to a family of pastoralists who've lived in the open grasslands of Central Asia for generations, moving with their horses and cattle between seasonal grazing lands. Her family sleeps in camps they can pack up in the morning, drifting with the seasons and the needs of the cattle. Ashva serves as a pathfinder for her people, scouting ahead of the main pack to map the terrain and ensure the safety of the route.`,
      `On this day, she spots a distant encampment unlike any she had ever seen. Unbeknownst to her people, they had begun to drift southward towards the Indian subcontinent, encountering farming communities for the first time. The tribes they encounter have formed into villages, living in permanent cities with farming as their main source of sustenance.`,
      `Reporting to her chief, Ashva eagerly awaits the exchange between the two peoples, as her tribe trades their hides and cattle in exchange for vegetables and crafted goods. The two groups intermix, with some tribesman choosing to stay behind, marrying into the agricultural village, and others choosing to explore the steppe alongside the pastoralists. The exchange leaves both groups culturally richer, bringing new histories and creations which result from the combination of peoples and cultures.`,
    ],
  },
]
